### ISSUE TITLE
Pusher is extremely slow on Android for subscriptions

### ISSUE THREAD

**Issue by creativepsyco** [pusher/pusher-java-client#51]
Hi I am using pusher to authenticate private channels. However, its extremely slow. The iOS library takes about 3 secs to subscribe successfully to the channels. However, the java client takes about 30~secs to complete the subscription process. Are there any specific reasons which might be causing this?

**Comment by leggetter** [comment]
There are two places where network connections are established:

1. The WebSocket connection to the Pusher WebSocket API
2. The HTTP authentication request for the private channel the app is attempting to subscribe to

I'd suggest that you add logging around the connection (e.g. logging [connection events](https://github.com/pusher/pusher-java-client#listening-to-connection-events)) and around the authentication (this may require a custom [HTTPAuthorizer](https://github.com/pusher/pusher-java-client/blob/master/src/main/java/com/pusher/client/util/HttpAuthorizer.java)).

That should help you identify where the slowdown is occuring.

**Comment by creativepsyco** [comment]
The WebSocket connection is pretty fast however the HTTP auth part slows it down I suppose it due to the way it is written down currently. I profiled the pusher method calls and found that a lot of the part is spent (almost 90%) in trying to convert to and from JSON (using GSON) and making the network request. Each network request takes about 400 msec to complete and since pusher uses a single thread for all the network operations, this happens one by one. The real times are obviously exaggerated, however, its close to the performance I am getting when not doing the profiling. I have about 50 private channels to subscribe to. 

![screen shot 2015-01-05 at 17 27 00](https://cloud.githubusercontent.com/assets/547235/5611343/88804de2-9500-11e4-99ae-98c06972b3df.png)

See [`toSubscribeMessage`][2]
I would suggest:
* Provide a batch mode for authenticating private channels since the end point remains the same, I believe this can be done, as [pusher-js-auth][1] has done it
* Perhaps a different transport payload other than JSON be used, protocol buffers?

[1]: https://github.com/dirkbonhomme/pusher-js-auth
[2]: https://github.com/pusher/pusher-java-client/blob/master/src/main/java/com/pusher/client/channel/impl/PrivateChannelImpl.java#L86

**Comment by mdpye** [comment]
Hi.

You can implement your own `Authorizer` to support this behaviour.

Once connected, you could get the socket id from `pusher.getConnection().getSocketId()` and use it and the channel names to do a single call to your endpoint which returns authorisation for several channels, then push this in to your own implementation of `Authorizer` which returns the pre-authorised responses rather than making network calls.

Alternatively, one can imagine an `Authorizer` which waits a short time after a request is made to see if any more follow and then batches the requests, however I think this will quickly become complicated with threading, as the `Authorizer` is expected to complete synchronously - waiting for more requests would be difficult without more sweeping changes to the library architecture, so I'd recommend pursuing the first option.

Finally, JSON encoding and decoding is unlikely to be any appreciable fraction of the time seen, it is probably heavily exaggerated in a tracing CPU profile as it involves a lot of reflective method calls.

**Comment by creativepsyco** [comment]
@mdpye Thanks for the advice, that's a great workaround I think the time is reduced to 3-4 secs I used a custom `Authorizer` to feed the JSON to pusher. I shall close this ticket.

**Comment by creativepsyco** [comment]
@leggetter Sure it's actually pretty simple. Basically you get the `socketId` when pusher is able to establish the connection. 
```java
        @Override
        public void onConnectionStateChange(ConnectionStateChange change) {
                // Save the socketId somewhere
                socketId = pusherClient.getConnection().getSocketId();
            }
        }
```

After that you can fire the request to your auth server to get all the Auth strings necessary for the various channels you want to subscribe to. This is a network request part.
```java
JSONObject response = getAuthResponseFromServer(socketId);
// response e.g.
// { 
//    "private-channel-xxx" : { "auth" : "12231:afdefbb"}
// }
```

In the end, just need to override the Authorizer to prevent it from making a network request, instead you supply it with the auth strings you obtained from the Authorisation server in batch.

```java
    @Override
    public String authorize(String channelName, String socketId) throws AuthorizationFailureException {
            return response.get(channelName); // lookup the batch response you recd previously
            // you can just return the JSON string received from the server if you transport protocol is JSON 
            // Since Pusher accepts JSON you will need to convert to their format if your transport protocol
            // is something else, like Protobuf etc. 
            // return batchResponse.get(channelName);
    }
```

I think the `HttpAuthorizer` can be extended to allow providing it all the auth strings it needs in one shot, so that it does not have to make the network request. It can accept a HashMap, JSONObject etc. This can be provided during initial pusher client configuration. Let me know if this sounds feasible I would love to contribute by submitting a PR.

**Comment by mdpye** [comment]
@creativepsyco One caveat I should point out for this scheme: If you become disconnected, when you reconnect, your socket ID will change and your authorisation will need to be re-done.

Slightly complicating this is the fact that the library tracks your subscriptions and will attempt to re-establish them with the server when you reconnect.

The reconnection itself is not automatic, you must call `connect()` again to kick it off.

I don't think there is currently a method in the library to clear out the cached subscription states, which you would need to do so that you can get the new socket ID and re-do the auth before the subscriptions are re-negotiated.

The order of events you *want* is:
- Initially: connected and subscribed, all is fine
- Become disconnected (e.g. 3G connection drops or switches to WiFi)
- Clear out subscriptions and auth responses (this step is not currently supported)
- Call `connect` to re-connect
- Get new socket id
- Make auth call to your server
- Re-subscribe with new auth tokens

The currently order of events you will find is:
- Initially: connected and subscribed, all is fine
- Become disconnected
- Call `connect

**Comment by mdpye** [comment]
@creativepsyco I have just realised a complication with this scheme.

If a client becomes disconnected, you will receive a ConnectionStateChange notifying you. Then after a short pause, you can call `connect` again to reconnect. The library tracks all the subscriptions you had set up before you were disconnected and tries to re-negotiate them automatically when the connection comes back, but when this happens you will have received a new socket ID and the auth responses won't be valid any more.

This requires a little thought. Unsubscribing from all channels when you're notified of a disconnect will work (so you have time to re-do the auth between reconnecting and resubscribing), but the latest released version don't allow unsubscribing while disconnected. I've just merged a pull request to master which enables this, you could experiment with that code.

**Comment by mdpye** [comment]
Bleugh. I thought I'd lost my first comment when I fat fingered something with `Ctrl` held down. Turns out I didn't. Both of the previous two comments are attempts to describe the same problem!

**Comment by creativepsyco** [comment]
Cool. I shall play around with the code to see if this strategy works, I think will just need to store the subscriptions in memory between reconnection and update auth responses from server.

**Comment by creativepsyco** [comment]
Here's the Gist: https://gist.github.com/creativepsyco/ae27651daaae20f2d86e Should I send a PR to get something similar included in the java client?

**Comment by Andy-Ho-GotIt** [comment]
Hi Pusher team, now i have this problem again, on some latest Android devices, it works well, it takes only 2-3 seconds to finish subscription, but with old Android device running Android 4.3, the authorization took a very long time to finish, i see the BatchAuthorization.java, but it just cache the authorization result, the problem is the authorize method consumes long time
